<?xml version="1.0" encoding="UTF-8"?>
<definitions name="PrintingServiceProvider"
	xmlns="http://schemas.xmlsoap.org/wsdl/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:doc="http://schemas.telekom.net/csdg-service-documentation_v01.01"
	xsi:schemaLocation="http://schemas.telekom.net/csdg-service-documentation_v01.01 ../../../../xsds-csdg/csdg-service-documentation_v01.01.xsd"
	targetNamespace="http://services.tint.telekom.net/EnterpSupp/EnterpEffAndPrjMgmt/PrintingService_v01.00/provider"
	xmlns:tns="http://services.tint.telekom.net/EnterpSupp/EnterpEffAndPrjMgmt/PrintingService_v01.00/provider"
	xmlns:service="http://services.tint.telekom.net/EnterpSupp/EnterpEffAndPrjMgmt/PrintingService_v01.00"
>
	<!--
		This wsdl has to be implemented by the Provider to enable him to receive requests from a Consumer.
		It imports the abstract wsdl and adds the sections "binding" and "service".
		(The Provider is the TECHNICAL provider, i.e. Server; The Consumer is the TECHNICAL consumer, i.e. Client)
	-->
	<documentation>
		<!-- !! @AUTHORS: INCREMENT VERSION NUMBER AND ADAPT "kind-of-creation" AFTER CHANGES !! -->
		<doc:transport version="01.00.000" version-date="2016-08-05">
			<doc:kind-of-creation>GENERATED</doc:kind-of-creation>
		</doc:transport>
	</documentation>
	<import namespace="http://services.tint.telekom.net/EnterpSupp/EnterpEffAndPrjMgmt/PrintingService_v01.00" location="PrintingService-RPC_v01.00.wsdl"/>
	<binding name="PrintingServiceBinding" type="service:PrintingService">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="print">
			<soap:operation soapAction=""/>
			<input>
				<soap:body use="literal"/>
			</input>
			<output>
				<soap:body use="literal"/>
			</output>
			<fault name="TechnicalFault">
				<soap:fault name="TechnicalFault" use="literal"/>
			</fault>
		</operation>
	</binding>
	<service name="PrintingServiceService">
		<port name="PrintingServicePort" binding="tns:PrintingServiceBinding">
			<soap:address location="http://REPLACE_WITH_ACTUAL_URL"/>
		</port>
	</service>
</definitions>