<?xml version="1.0" encoding="UTF-8"?>
<definitions name="ShipmentDistribute" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:doc="http://schemas.telekom.net/csdg-service-documentation_v01.01" xsi:schemaLocation="http://schemas.telekom.net/csdg-service-documentation_v01.01 ../../../../xsds-csdg/csdg-service-documentation_v01.01.xsd" xmlns:csdg="http://schemas.telekom.net/csdg_v01.01" targetNamespace="http://services.tint.telekom.net/EnterpSupp/EnterpEffAndPrjMgmt/ShipmentDistribute_v01.00" xmlns:tns="http://services.tint.telekom.net/EnterpSupp/EnterpEffAndPrjMgmt/ShipmentDistribute_v01.00">
  <documentation>
    <!-- !! @AUTHORS: INCREMENT VERSION NUMBER AND ADAPT "kind-of-creation" AFTER CHANGES !! -->
    <doc:service governance-area="tint" domain="EnterpSupp" functional-component="EnterpEffAndPrjMgmt" version="01.00.000" version-date="2017-05-10" isLogicalService="true">
      <doc:description>
Updated on 01.06.2017 10:45:52, UTC
14117	01.06.2017 10:04:33	Version fix. MOM deleted
13980	23.05.2017 08:08:18	Transporatation zone

Updated on 10.05.2017 08:59:12, UTC
13855	10.05.2017 08:58:13	Corrections for CSDG validator

Updated on 30.03.2017 09:32:06, UTC
13481	30.03.2017 09:29:10	Transportation zone field added to address
12156	13.12.2016 10:18:47	Incident 1060031193

Updated on 04.03.2016 09:06:52, UTC
7524	29.02.2016 13:24:20	StreetSupplimentary and Location fields in address

Updated on 09.09.2015 17:21:37, UTC
6080	09.09.2015 17:21:05	Occurrence changed from 0..1 to 1..1 for base xsd types. Pattern \d+ removed

Updated on 27.05.2015 18:36:13, UTC
5442	20.05.2015 16:01:55	Byte order mark deleted. utf-8 -&gt; UTF-8
5437	20.05.2015 09:35:37	Version updated for wsdls for 15C
5412	15.05.2015 19:53:07	Serial number fields renamed
5396	13.05.2015 09:49:20	default namesapce fixed
5393	13.05.2015 09:16:09	References fixed
5367	11.05.2015 11:58:22	
5365	11.05.2015 10:03:44	
5067	11.03.2015 14:56:19	
5041	11.03.2015 08:25:36	
5031	10.03.2015 16:06:32	
4995	06.03.2015 14:11:58	Minor changes
4962	05.03.2015 17:42:45	Addresses and floc
4953	05.03.2015 15:25:02	ServicePackageItem.xsd and services
4608	14.01.2015 09:42:27	Language added to transportation point description
4413	25.11.2014 11:59:17	CSDG. One operation = one service.
4248	11.11.2014 14:27:44	New interface
4232	08.11.2014 21:06:45	New Wsdls
3693	24.09.2014 15:13:12	SoaBP wsdls

				-------------------------- @TODO:DESCRIBE_ME - Service "ShipmentDistribute" -----------------------------
			</doc:description>
      <doc:designer>mailto:Augustinus.Deimel@telekom.de</doc:designer>
      <doc:kind-of-creation>GENERATED</doc:kind-of-creation>
      <doc:change predecessorVersion="01.00.000" by="A.Deimel" date="2014-10-20" doc:lang="en">14117</doc:change>
    </doc:service>
  </documentation>
  <types>
    <xsd:schema targetNamespace="http://services.tint.telekom.net/EnterpSupp/EnterpEffAndPrjMgmt/ShipmentDistribute_v01.00" elementFormDefault="qualified" attributeFormDefault="unqualified" version="01.00" xmlns:types="http://services.tint.telekom.net/EnterpSupp/EnterpEffAndPrjMgmt/ShipmentDistribute_v01.00/types">
      <!-- ****************************************************************** -->
      <xsd:import namespace="http://schemas.telekom.net/csdg_v01.01" schemaLocation="../../../../xsds-csdg/csdg_v01.01.xsd" />
      <xsd:import namespace="http://services.tint.telekom.net/EnterpSupp/EnterpEffAndPrjMgmt/ShipmentDistribute_v01.00/types" schemaLocation="ShipmentDistribute_v01.00.xsd" />
      <!-- ****************************************************************** -->
      <xsd:element name="distributeChangesAsync" type="types:DistributeChangesAsyncType" />
    </xsd:schema>
  </types>
  <!-- ****************************************************************** -->
  <!-- Messages : -->
  <!-- ****************************************************************** -->
  <message name="DistributeChangesAsync">
    <part name="parameters" element="tns:distributeChangesAsync" />
  </message>
  <message name="EmptyTechnicalResponse">
    <part name="parameters" element="csdg:empty" />
  </message>
  <message name="TechnicalFault">
    <part name="parameters" element="csdg:technicalFault" />
  </message>
  <!-- ****************************************************************** -->
  <!-- PortTypes : -->
  <!-- ****************************************************************** -->
  <!-- Consumer : -->
  <portType name="ShipmentDistributeConsumer">
    <operation name="distributeChangesAsync">
      <documentation>
        <doc:operation mep="Notification" access="ReadOnly">
          <doc:description>
						-------------------------- @TODO:DESCRIBE_ME - Operation "distributeChangesAsync" -----------------------------
					</doc:description>
        </doc:operation>
      </documentation>
      <input message="tns:DistributeChangesAsync" />
      <output message="tns:EmptyTechnicalResponse" />
      <fault message="tns:TechnicalFault" name="TechnicalFault" />
    </operation>
  </portType>
</definitions>