//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl vygenerován nástrojem.
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny, pokud
//     pokud bude kód znovu vygenerován.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskListService
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.telekom.net/csdg_v01.01")]
    public partial class TCTechnicalFaultInfo : TCFaultInfo
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TCBusinessFaultInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TCTechnicalFaultInfo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.telekom.net/csdg_v01.01")]
    public partial class TCFaultInfo
    {
        
        private TCContext contextField;
        
        private System.DateTime timestampField;
        
        private string errorCodeField;
        
        private string errorLocationField;
        
        private int severityField;
        
        private TCDescription[] descriptionField;
        
        private TCProperty[] propertyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public TCContext context
        {
            get
            {
                return this.contextField;
            }
            set
            {
                this.contextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime timestamp
        {
            get
            {
                return this.timestampField;
            }
            set
            {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string errorLocation
        {
            get
            {
                return this.errorLocationField;
            }
            set
            {
                this.errorLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int severity
        {
            get
            {
                return this.severityField;
            }
            set
            {
                this.severityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("description", Order=5)]
        public TCDescription[] description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("property", Order=6)]
        public TCProperty[] property
        {
            get
            {
                return this.propertyField;
            }
            set
            {
                this.propertyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.telekom.net/csdg_v01.01")]
    public partial class TCContext
    {
        
        private TCTechnicalContext technicalContextField;
        
        private TCBusinessContext businessContextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public TCTechnicalContext technicalContext
        {
            get
            {
                return this.technicalContextField;
            }
            set
            {
                this.technicalContextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TCBusinessContext businessContext
        {
            get
            {
                return this.businessContextField;
            }
            set
            {
                this.businessContextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.telekom.net/csdg_v01.01")]
    public partial class TCTechnicalContext
    {
        
        private string fromField;
        
        private string routingInfoField;
        
        private string messageIdField;
        
        private string relatesToMessageIdField;
        
        private System.DateTime currentSenderTimestampUTCField;
        
        private string expiryOffsetInMillisField;
        
        private short priorityField;
        
        private bool priorityFieldSpecified;
        
        private string replyStateField;
        
        private TCProperty[] propertyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string from
        {
            get
            {
                return this.fromField;
            }
            set
            {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string routingInfo
        {
            get
            {
                return this.routingInfoField;
            }
            set
            {
                this.routingInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string messageId
        {
            get
            {
                return this.messageIdField;
            }
            set
            {
                this.messageIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string relatesToMessageId
        {
            get
            {
                return this.relatesToMessageIdField;
            }
            set
            {
                this.relatesToMessageIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime currentSenderTimestampUTC
        {
            get
            {
                return this.currentSenderTimestampUTCField;
            }
            set
            {
                this.currentSenderTimestampUTCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=5)]
        public string expiryOffsetInMillis
        {
            get
            {
                return this.expiryOffsetInMillisField;
            }
            set
            {
                this.expiryOffsetInMillisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public short priority
        {
            get
            {
                return this.priorityField;
            }
            set
            {
                this.priorityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool prioritySpecified
        {
            get
            {
                return this.priorityFieldSpecified;
            }
            set
            {
                this.priorityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string replyState
        {
            get
            {
                return this.replyStateField;
            }
            set
            {
                this.replyStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("property", Order=8)]
        public TCProperty[] property
        {
            get
            {
                return this.propertyField;
            }
            set
            {
                this.propertyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.telekom.net/csdg_v01.01")]
    public partial class TCProperty
    {
        
        private string nameField;
        
        private TCPropertyType typeField;
        
        private bool typeFieldSpecified;
        
        private string policyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public TCPropertyType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified
        {
            get
            {
                return this.typeFieldSpecified;
            }
            set
            {
                this.typeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string policy
        {
            get
            {
                return this.policyField;
            }
            set
            {
                this.policyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.telekom.net/csdg_v01.01")]
    public enum TCPropertyType
    {
        
        /// <remarks/>
        @string,
        
        /// <remarks/>
        @int,
        
        /// <remarks/>
        boolean,
        
        /// <remarks/>
        @float,
        
        /// <remarks/>
        date,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.telekom.net/csdg_v01.01")]
    public partial class TCDescription
    {
        
        private string langField;
        
        private string descIdField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string lang
        {
            get
            {
                return this.langField;
            }
            set
            {
                this.langField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string descId
        {
            get
            {
                return this.descIdField;
            }
            set
            {
                this.descIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://telekom.de/xi/NGERP_CORE_PSLINT/global/v1")]
    public partial class DT_ProcessingMessage
    {
        
        private string typeField;
        
        private string textField;
        
        private string codeField;
        
        private DT_ProcessingMessageParameters[] parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=2)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Parameters", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public DT_ProcessingMessageParameters[] Parameters
        {
            get
            {
                return this.parametersField;
            }
            set
            {
                this.parametersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://telekom.de/xi/NGERP_CORE_PSLINT/global/v1")]
    public partial class DT_ProcessingMessageParameters
    {
        
        private string nameField;
        
        private string valueField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://telekom.de/xi/NGERP_CORE_PSLINT/global/v1")]
    public partial class ClassificationDto
    {
        
        private string actionField;
        
        private string selectorField;
        
        private string[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Selector
        {
            get
            {
                return this.selectorField;
            }
            set
            {
                this.selectorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Value", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string[] Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://telekom.de/xi/NGERP_CORE_PSLINT/global/v1/MM")]
    public partial class ServicePackageItem2Dto
    {
        
        private string actionField;
        
        private string packageIdField;
        
        private string internalNumberField;
        
        private string externalNumberField;
        
        private string serviceIdField;
        
        private decimal quantityField;
        
        private bool quantityFieldSpecified;
        
        private string unitIdField;
        
        private decimal priceUnitField;
        
        private bool priceUnitFieldSpecified;
        
        private decimal grossPriceField;
        
        private bool grossPriceFieldSpecified;
        
        private decimal netPriceField;
        
        private bool netPriceFieldSpecified;
        
        private string costElementField;
        
        private string sourcePackageIdField;
        
        private string sourcePackageItemInternalNumberField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string PackageId
        {
            get
            {
                return this.packageIdField;
            }
            set
            {
                this.packageIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string InternalNumber
        {
            get
            {
                return this.internalNumberField;
            }
            set
            {
                this.internalNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ExternalNumber
        {
            get
            {
                return this.externalNumberField;
            }
            set
            {
                this.externalNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ServiceId
        {
            get
            {
                return this.serviceIdField;
            }
            set
            {
                this.serviceIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal Quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuantitySpecified
        {
            get
            {
                return this.quantityFieldSpecified;
            }
            set
            {
                this.quantityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string UnitId
        {
            get
            {
                return this.unitIdField;
            }
            set
            {
                this.unitIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public decimal PriceUnit
        {
            get
            {
                return this.priceUnitField;
            }
            set
            {
                this.priceUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PriceUnitSpecified
        {
            get
            {
                return this.priceUnitFieldSpecified;
            }
            set
            {
                this.priceUnitFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public decimal GrossPrice
        {
            get
            {
                return this.grossPriceField;
            }
            set
            {
                this.grossPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GrossPriceSpecified
        {
            get
            {
                return this.grossPriceFieldSpecified;
            }
            set
            {
                this.grossPriceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public decimal NetPrice
        {
            get
            {
                return this.netPriceField;
            }
            set
            {
                this.netPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NetPriceSpecified
        {
            get
            {
                return this.netPriceFieldSpecified;
            }
            set
            {
                this.netPriceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string CostElement
        {
            get
            {
                return this.costElementField;
            }
            set
            {
                this.costElementField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string SourcePackageId
        {
            get
            {
                return this.sourcePackageIdField;
            }
            set
            {
                this.sourcePackageIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string SourcePackageItemInternalNumber
        {
            get
            {
                return this.sourcePackageItemInternalNumberField;
            }
            set
            {
                this.sourcePackageItemInternalNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://telekom.de/xi/NGERP_CORE_PSLINT/global/v1/PM")]
    public partial class DT_TaskListId
    {
        
        private string typeIdField;
        
        private string groupField;
        
        private string groupCounterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TypeId
        {
            get
            {
                return this.typeIdField;
            }
            set
            {
                this.typeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Group
        {
            get
            {
                return this.groupField;
            }
            set
            {
                this.groupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string GroupCounter
        {
            get
            {
                return this.groupCounterField;
            }
            set
            {
                this.groupCounterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://telekom.de/xi/NGERP_CORE_PSLINT/global/v1/PM")]
    public partial class TaskListDto
    {
        
        private string actionField;
        
        private DT_TaskListId idField;
        
        private TaskListDtoHeader headerField;
        
        private bool operationsAllField;
        
        private bool operationsAllFieldSpecified;
        
        private TaskListDtoOperations[] operationsField;
        
        private bool classificationsAllField;
        
        private bool classificationsAllFieldSpecified;
        
        private ClassificationDto[] classificationsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public DT_TaskListId Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public TaskListDtoHeader Header
        {
            get
            {
                return this.headerField;
            }
            set
            {
                this.headerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool OperationsAll
        {
            get
            {
                return this.operationsAllField;
            }
            set
            {
                this.operationsAllField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OperationsAllSpecified
        {
            get
            {
                return this.operationsAllFieldSpecified;
            }
            set
            {
                this.operationsAllFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Operations", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public TaskListDtoOperations[] Operations
        {
            get
            {
                return this.operationsField;
            }
            set
            {
                this.operationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public bool ClassificationsAll
        {
            get
            {
                return this.classificationsAllField;
            }
            set
            {
                this.classificationsAllField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ClassificationsAllSpecified
        {
            get
            {
                return this.classificationsAllFieldSpecified;
            }
            set
            {
                this.classificationsAllFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Classifications", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public ClassificationDto[] Classifications
        {
            get
            {
                return this.classificationsField;
            }
            set
            {
                this.classificationsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://telekom.de/xi/NGERP_CORE_PSLINT/global/v1/PM")]
    public partial class TaskListDtoHeader
    {
        
        private System.DateTime validFromField;
        
        private bool validFromFieldSpecified;
        
        private string descriptionField;
        
        private string assemblyIdField;
        
        private string maintenancePlanningPlantIdField;
        
        private string plannerGroupField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=0)]
        public System.DateTime ValidFrom
        {
            get
            {
                return this.validFromField;
            }
            set
            {
                this.validFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValidFromSpecified
        {
            get
            {
                return this.validFromFieldSpecified;
            }
            set
            {
                this.validFromFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string AssemblyId
        {
            get
            {
                return this.assemblyIdField;
            }
            set
            {
                this.assemblyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string MaintenancePlanningPlantId
        {
            get
            {
                return this.maintenancePlanningPlantIdField;
            }
            set
            {
                this.maintenancePlanningPlantIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string PlannerGroup
        {
            get
            {
                return this.plannerGroupField;
            }
            set
            {
                this.plannerGroupField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://telekom.de/xi/NGERP_CORE_PSLINT/global/v1/PM")]
    public partial class TaskListDtoOperations
    {
        
        private string actionField;
        
        private string numberInNodeField;
        
        private string internalCounterField;
        
        private System.DateTime validFromField;
        
        private bool validFromFieldSpecified;
        
        private string numberField;
        
        private string superiorOperationNumberInNodeField;
        
        private string controlKeyField;
        
        private string descriptionField;
        
        private string workAmountUnitIdField;
        
        private decimal workAmountField;
        
        private bool workAmountFieldSpecified;
        
        private bool componentsAllField;
        
        private bool componentsAllFieldSpecified;
        
        private TaskListDtoOperationsComponents[] componentsField;
        
        private bool servicesAllField;
        
        private bool servicesAllFieldSpecified;
        
        private ServicePackageItem2Dto[] servicesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string NumberInNode
        {
            get
            {
                return this.numberInNodeField;
            }
            set
            {
                this.numberInNodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string InternalCounter
        {
            get
            {
                return this.internalCounterField;
            }
            set
            {
                this.internalCounterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=3)]
        public System.DateTime ValidFrom
        {
            get
            {
                return this.validFromField;
            }
            set
            {
                this.validFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValidFromSpecified
        {
            get
            {
                return this.validFromFieldSpecified;
            }
            set
            {
                this.validFromFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string SuperiorOperationNumberInNode
        {
            get
            {
                return this.superiorOperationNumberInNodeField;
            }
            set
            {
                this.superiorOperationNumberInNodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ControlKey
        {
            get
            {
                return this.controlKeyField;
            }
            set
            {
                this.controlKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string WorkAmountUnitId
        {
            get
            {
                return this.workAmountUnitIdField;
            }
            set
            {
                this.workAmountUnitIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public decimal WorkAmount
        {
            get
            {
                return this.workAmountField;
            }
            set
            {
                this.workAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WorkAmountSpecified
        {
            get
            {
                return this.workAmountFieldSpecified;
            }
            set
            {
                this.workAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public bool ComponentsAll
        {
            get
            {
                return this.componentsAllField;
            }
            set
            {
                this.componentsAllField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ComponentsAllSpecified
        {
            get
            {
                return this.componentsAllFieldSpecified;
            }
            set
            {
                this.componentsAllFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Components", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public TaskListDtoOperationsComponents[] Components
        {
            get
            {
                return this.componentsField;
            }
            set
            {
                this.componentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public bool ServicesAll
        {
            get
            {
                return this.servicesAllField;
            }
            set
            {
                this.servicesAllField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ServicesAllSpecified
        {
            get
            {
                return this.servicesAllFieldSpecified;
            }
            set
            {
                this.servicesAllFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Services", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public ServicePackageItem2Dto[] Services
        {
            get
            {
                return this.servicesField;
            }
            set
            {
                this.servicesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://telekom.de/xi/NGERP_CORE_PSLINT/global/v1/PM")]
    public partial class TaskListDtoOperationsComponents
    {
        
        private string actionField;
        
        private string allocationNumberField;
        
        private string counterField;
        
        private System.DateTime validFromField;
        
        private bool validFromFieldSpecified;
        
        private string materialIdField;
        
        private decimal quantityField;
        
        private bool quantityFieldSpecified;
        
        private string unitIdField;
        
        private string categoryIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string AllocationNumber
        {
            get
            {
                return this.allocationNumberField;
            }
            set
            {
                this.allocationNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Counter
        {
            get
            {
                return this.counterField;
            }
            set
            {
                this.counterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=3)]
        public System.DateTime ValidFrom
        {
            get
            {
                return this.validFromField;
            }
            set
            {
                this.validFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValidFromSpecified
        {
            get
            {
                return this.validFromFieldSpecified;
            }
            set
            {
                this.validFromFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string MaterialId
        {
            get
            {
                return this.materialIdField;
            }
            set
            {
                this.materialIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal Quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuantitySpecified
        {
            get
            {
                return this.quantityFieldSpecified;
            }
            set
            {
                this.quantityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string UnitId
        {
            get
            {
                return this.unitIdField;
            }
            set
            {
                this.unitIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string CategoryId
        {
            get
            {
                return this.categoryIdField;
            }
            set
            {
                this.categoryIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://telekom.de/xi/NGERP_CORE_PSLINT/global/v1/PM")]
    public partial class TaskListFilterDto
    {
        
        private TaskListFilterDtoCriterions criterionsField;
        
        private TaskListFilterDtoReturnData returnDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public TaskListFilterDtoCriterions Criterions
        {
            get
            {
                return this.criterionsField;
            }
            set
            {
                this.criterionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public TaskListFilterDtoReturnData ReturnData
        {
            get
            {
                return this.returnDataField;
            }
            set
            {
                this.returnDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://telekom.de/xi/NGERP_CORE_PSLINT/global/v1/PM")]
    public partial class TaskListFilterDtoCriterions
    {
        
        private TaskListFilterDtoCriterionsIds[] idsField;
        
        private bool classificationFiltersJoinField;
        
        private bool classificationFiltersJoinFieldSpecified;
        
        private TaskListFilterDtoCriterionsClassification[] classificationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Ids", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public TaskListFilterDtoCriterionsIds[] Ids
        {
            get
            {
                return this.idsField;
            }
            set
            {
                this.idsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool ClassificationFiltersJoin
        {
            get
            {
                return this.classificationFiltersJoinField;
            }
            set
            {
                this.classificationFiltersJoinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ClassificationFiltersJoinSpecified
        {
            get
            {
                return this.classificationFiltersJoinFieldSpecified;
            }
            set
            {
                this.classificationFiltersJoinFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Classification", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public TaskListFilterDtoCriterionsClassification[] Classification
        {
            get
            {
                return this.classificationField;
            }
            set
            {
                this.classificationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://telekom.de/xi/NGERP_CORE_PSLINT/global/v1/PM")]
    public partial class TaskListFilterDtoCriterionsIds
    {
        
        private string typeIdField;
        
        private string groupField;
        
        private string groupCounterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TypeId
        {
            get
            {
                return this.typeIdField;
            }
            set
            {
                this.typeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Group
        {
            get
            {
                return this.groupField;
            }
            set
            {
                this.groupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string GroupCounter
        {
            get
            {
                return this.groupCounterField;
            }
            set
            {
                this.groupCounterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://telekom.de/xi/NGERP_CORE_PSLINT/global/v1/PM")]
    public partial class TaskListFilterDtoCriterionsClassification
    {
        
        private string selectorField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Selector
        {
            get
            {
                return this.selectorField;
            }
            set
            {
                this.selectorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://telekom.de/xi/NGERP_CORE_PSLINT/global/v1/PM")]
    public partial class TaskListFilterDtoReturnData
    {
        
        private bool headerField;
        
        private bool headerFieldSpecified;
        
        private bool operationsField;
        
        private bool operationsFieldSpecified;
        
        private bool componentsField;
        
        private bool componentsFieldSpecified;
        
        private bool servicesField;
        
        private bool servicesFieldSpecified;
        
        private bool classificationsField;
        
        private bool classificationsFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool Header
        {
            get
            {
                return this.headerField;
            }
            set
            {
                this.headerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HeaderSpecified
        {
            get
            {
                return this.headerFieldSpecified;
            }
            set
            {
                this.headerFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool Operations
        {
            get
            {
                return this.operationsField;
            }
            set
            {
                this.operationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OperationsSpecified
        {
            get
            {
                return this.operationsFieldSpecified;
            }
            set
            {
                this.operationsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool Components
        {
            get
            {
                return this.componentsField;
            }
            set
            {
                this.componentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ComponentsSpecified
        {
            get
            {
                return this.componentsFieldSpecified;
            }
            set
            {
                this.componentsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool Services
        {
            get
            {
                return this.servicesField;
            }
            set
            {
                this.servicesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ServicesSpecified
        {
            get
            {
                return this.servicesFieldSpecified;
            }
            set
            {
                this.servicesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool Classifications
        {
            get
            {
                return this.classificationsField;
            }
            set
            {
                this.classificationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ClassificationsSpecified
        {
            get
            {
                return this.classificationsFieldSpecified;
            }
            set
            {
                this.classificationsFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.telekom.net/csdg_v01.01")]
    public partial class TCBusinessContext
    {
        
        private string processIdField;
        
        private string processTypeIdField;
        
        private string messageGroupIdField;
        
        private string processStepTypeIdField;
        
        private string parentProcessIdField;
        
        private TCProperty[] propertyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string processId
        {
            get
            {
                return this.processIdField;
            }
            set
            {
                this.processIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string processTypeId
        {
            get
            {
                return this.processTypeIdField;
            }
            set
            {
                this.processTypeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string messageGroupId
        {
            get
            {
                return this.messageGroupIdField;
            }
            set
            {
                this.messageGroupIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string processStepTypeId
        {
            get
            {
                return this.processStepTypeIdField;
            }
            set
            {
                this.processStepTypeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string parentProcessId
        {
            get
            {
                return this.parentProcessIdField;
            }
            set
            {
                this.parentProcessIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("property", Order=5)]
        public TCProperty[] property
        {
            get
            {
                return this.propertyField;
            }
            set
            {
                this.propertyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.telekom.net/csdg_v01.01")]
    public partial class TCBusinessFaultInfo : TCFaultInfo
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.tint.telekom.net/EnterpSupp/EnterpEffAndPrjMgmt/TaskList_v01.00", ConfigurationName="TaskListService.TaskList")]
    public interface TaskList
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(TaskListService.TCTechnicalFaultInfo), Action="", Name="technicalFault", Namespace="http://schemas.telekom.net/csdg_v01.01")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TCFaultInfo))]
        TaskListService.getByFilterResponse getByFilter(TaskListService.getByFilterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TaskListService.getByFilterResponse> getByFilterAsync(TaskListService.getByFilterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(TaskListService.TCTechnicalFaultInfo), Action="", Name="technicalFault", Namespace="http://schemas.telekom.net/csdg_v01.01")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TCFaultInfo))]
        TaskListService.getChangesResponse getChanges(TaskListService.getChangesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TaskListService.getChangesResponse> getChangesAsync(TaskListService.getChangesRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://services.tint.telekom.net/EnterpSupp/EnterpEffAndPrjMgmt/TaskList_v01.00/t" +
        "ypes")]
    public partial class GetByFilterRequestTypeData
    {
        
        private TaskListFilterDto filterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public TaskListFilterDto Filter
        {
            get
            {
                return this.filterField;
            }
            set
            {
                this.filterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://services.tint.telekom.net/EnterpSupp/EnterpEffAndPrjMgmt/TaskList_v01.00/t" +
        "ypes")]
    public partial class GetByFilterResponseTypeData
    {
        
        private TaskListDto[] taskListsField;
        
        private DT_ProcessingMessage[] messagesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TaskLists", Order=0)]
        public TaskListDto[] TaskLists
        {
            get
            {
                return this.taskListsField;
            }
            set
            {
                this.taskListsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Messages", Order=1)]
        public DT_ProcessingMessage[] Messages
        {
            get
            {
                return this.messagesField;
            }
            set
            {
                this.messagesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getByFilter", WrapperNamespace="http://services.tint.telekom.net/EnterpSupp/EnterpEffAndPrjMgmt/TaskList_v01.00", IsWrapped=true)]
    public partial class getByFilterRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tint.telekom.net/EnterpSupp/EnterpEffAndPrjMgmt/TaskList_v01.00/t" +
            "ypes", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://services.tint.telekom.net/EnterpSupp/EnterpEffAndPrjMgmt/TaskList_v01.00/t" +
            "ypes")]
        public TaskListService.TCContext context;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tint.telekom.net/EnterpSupp/EnterpEffAndPrjMgmt/TaskList_v01.00/t" +
            "ypes", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://services.tint.telekom.net/EnterpSupp/EnterpEffAndPrjMgmt/TaskList_v01.00/t" +
            "ypes")]
        public TaskListService.GetByFilterRequestTypeData data;
        
        public getByFilterRequest()
        {
        }
        
        public getByFilterRequest(TaskListService.TCContext context, TaskListService.GetByFilterRequestTypeData data)
        {
            this.context = context;
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getByFilterResponse", WrapperNamespace="http://services.tint.telekom.net/EnterpSupp/EnterpEffAndPrjMgmt/TaskList_v01.00", IsWrapped=true)]
    public partial class getByFilterResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tint.telekom.net/EnterpSupp/EnterpEffAndPrjMgmt/TaskList_v01.00/t" +
            "ypes", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://services.tint.telekom.net/EnterpSupp/EnterpEffAndPrjMgmt/TaskList_v01.00/t" +
            "ypes")]
        public TaskListService.TCContext context;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tint.telekom.net/EnterpSupp/EnterpEffAndPrjMgmt/TaskList_v01.00/t" +
            "ypes", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://services.tint.telekom.net/EnterpSupp/EnterpEffAndPrjMgmt/TaskList_v01.00/t" +
            "ypes")]
        public TaskListService.GetByFilterResponseTypeData data;
        
        public getByFilterResponse()
        {
        }
        
        public getByFilterResponse(TaskListService.TCContext context, TaskListService.GetByFilterResponseTypeData data)
        {
            this.context = context;
            this.data = data;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://telekom.de/xi/NGERP_CORE_PSLINT/global/v1")]
    public partial class ObjectChangeFilterDto
    {
        
        private string idField;
        
        private decimal versionTimestampField;
        
        private bool fullObjectField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal VersionTimestamp
        {
            get
            {
                return this.versionTimestampField;
            }
            set
            {
                this.versionTimestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool FullObject
        {
            get
            {
                return this.fullObjectField;
            }
            set
            {
                this.fullObjectField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://services.tint.telekom.net/EnterpSupp/EnterpEffAndPrjMgmt/TaskList_v01.00/t" +
        "ypes")]
    public partial class GetChangesResponseTypeData
    {
        
        private TaskListDto[] taskListsField;
        
        private DT_ProcessingMessage[] messagesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TaskLists", Order=0)]
        public TaskListDto[] TaskLists
        {
            get
            {
                return this.taskListsField;
            }
            set
            {
                this.taskListsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Messages", Order=1)]
        public DT_ProcessingMessage[] Messages
        {
            get
            {
                return this.messagesField;
            }
            set
            {
                this.messagesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getChanges", WrapperNamespace="http://services.tint.telekom.net/EnterpSupp/EnterpEffAndPrjMgmt/TaskList_v01.00", IsWrapped=true)]
    public partial class getChangesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tint.telekom.net/EnterpSupp/EnterpEffAndPrjMgmt/TaskList_v01.00/t" +
            "ypes", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://services.tint.telekom.net/EnterpSupp/EnterpEffAndPrjMgmt/TaskList_v01.00/t" +
            "ypes")]
        public TaskListService.TCContext context;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tint.telekom.net/EnterpSupp/EnterpEffAndPrjMgmt/TaskList_v01.00/t" +
            "ypes", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://services.tint.telekom.net/EnterpSupp/EnterpEffAndPrjMgmt/TaskList_v01.00/t" +
            "ypes")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Filters", IsNullable=false)]
        public TaskListService.ObjectChangeFilterDto[] data;
        
        public getChangesRequest()
        {
        }
        
        public getChangesRequest(TaskListService.TCContext context, TaskListService.ObjectChangeFilterDto[] data)
        {
            this.context = context;
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getChangesResponse", WrapperNamespace="http://services.tint.telekom.net/EnterpSupp/EnterpEffAndPrjMgmt/TaskList_v01.00", IsWrapped=true)]
    public partial class getChangesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tint.telekom.net/EnterpSupp/EnterpEffAndPrjMgmt/TaskList_v01.00/t" +
            "ypes", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://services.tint.telekom.net/EnterpSupp/EnterpEffAndPrjMgmt/TaskList_v01.00/t" +
            "ypes")]
        public TaskListService.TCContext context;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.tint.telekom.net/EnterpSupp/EnterpEffAndPrjMgmt/TaskList_v01.00/t" +
            "ypes", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://services.tint.telekom.net/EnterpSupp/EnterpEffAndPrjMgmt/TaskList_v01.00/t" +
            "ypes")]
        public TaskListService.GetChangesResponseTypeData data;
        
        public getChangesResponse()
        {
        }
        
        public getChangesResponse(TaskListService.TCContext context, TaskListService.GetChangesResponseTypeData data)
        {
            this.context = context;
            this.data = data;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface TaskListChannel : TaskListService.TaskList, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class TaskListClient : System.ServiceModel.ClientBase<TaskListService.TaskList>, TaskListService.TaskList
    {
        
        /// <summary>
        /// Chcete-li nakonfigurovat koncový bod služby, implementujte tuto částečnou metodu.
        /// </summary>
        /// <param name="serviceEndpoint">Koncový bod, který má být nakonfigurován</param>
        /// <param name="clientCredentials">Přihlašovací údaje klienta</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TaskListClient() : 
                base(TaskListClient.GetDefaultBinding(), TaskListClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.TaskListPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TaskListClient(EndpointConfiguration endpointConfiguration) : 
                base(TaskListClient.GetBindingForEndpoint(endpointConfiguration), TaskListClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TaskListClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TaskListClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TaskListClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TaskListClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TaskListClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public TaskListService.getByFilterResponse getByFilter(TaskListService.getByFilterRequest request)
        {
            return base.Channel.getByFilter(request);
        }
        
        public System.Threading.Tasks.Task<TaskListService.getByFilterResponse> getByFilterAsync(TaskListService.getByFilterRequest request)
        {
            return base.Channel.getByFilterAsync(request);
        }
        
        public TaskListService.getChangesResponse getChanges(TaskListService.getChangesRequest request)
        {
            return base.Channel.getChanges(request);
        }
        
        public System.Threading.Tasks.Task<TaskListService.getChangesResponse> getChangesAsync(TaskListService.getChangesRequest request)
        {
            return base.Channel.getChangesAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TaskListPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Nelze najít koncový bod s názvem {0}.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TaskListPort))
            {
                return new System.ServiceModel.EndpointAddress("https://10.254.118.59:8643/csdg/rpc/OneERP2-Q/tmcz.telekom.it.architecture.MT/MT/" +
                        "PSLIntTaskList/up");
            }
            throw new System.InvalidOperationException(string.Format("Nelze najít koncový bod s názvem {0}.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return TaskListClient.GetBindingForEndpoint(EndpointConfiguration.TaskListPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return TaskListClient.GetEndpointAddress(EndpointConfiguration.TaskListPort);
        }
        
        public enum EndpointConfiguration
        {
            
            TaskListPort,
        }
    }
}
