<?xml version="1.0" encoding="UTF-8"?>
<definitions name="PurchaseDocumentDistribute" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:doc="http://schemas.telekom.net/csdg-service-documentation_v01.01" xsi:schemaLocation="http://schemas.telekom.net/csdg-service-documentation_v01.01 ../../../../xsds-csdg/csdg-service-documentation_v01.01.xsd" xmlns:csdg="http://schemas.telekom.net/csdg_v01.01" targetNamespace="http://services.tint.telekom.net/EnterpSupp/EnterpEffAndPrjMgmt/PurchaseDocumentDistribute_v01.00" xmlns:tns="http://services.tint.telekom.net/EnterpSupp/EnterpEffAndPrjMgmt/PurchaseDocumentDistribute_v01.00">
  <documentation>
    <!-- !! @AUTHORS: INCREMENT VERSION NUMBER AND ADAPT "kind-of-creation" AFTER CHANGES !! -->
    <doc:service governance-area="tint" domain="EnterpSupp" functional-component="EnterpEffAndPrjMgmt" version="01.00.000" version-date="2017-05-10" isLogicalService="true">
      <doc:description>
Updated on 01.06.2017 10:45:52, UTC
14117	01.06.2017 10:04:33	Version fix. MOM deleted

Updated on 10.05.2017 08:59:12, UTC
13855	10.05.2017 08:58:13	Corrections for CSDG validator

Updated on 27.05.2015 18:36:12, UTC
5442	20.05.2015 16:01:55	Byte order mark deleted. utf-8 -&gt; UTF-8
5437	20.05.2015 09:35:37	Version updated for wsdls for 15C
4413	25.11.2014 11:59:17	CSDG. One operation = one service.
4316	17.11.2014 17:19:16	Changes for csdg
4168	06.11.2014 12:11:59	New wsdls
3693	24.09.2014 15:13:12	SoaBP wsdls

				-------------------------- @TODO:DESCRIBE_ME - Service "PurchaseDocumentDistribute" -----------------------------
			</doc:description>
      <doc:designer>mailto:Augustinus.Deimel@telekom.de</doc:designer>
      <doc:kind-of-creation>GENERATED</doc:kind-of-creation>
      <doc:change predecessorVersion="01.00.000" by="A.Deimel" date="2014-10-20" doc:lang="en">14117</doc:change>
    </doc:service>
  </documentation>
  <types>
    <xsd:schema targetNamespace="http://services.tint.telekom.net/EnterpSupp/EnterpEffAndPrjMgmt/PurchaseDocumentDistribute_v01.00" elementFormDefault="qualified" attributeFormDefault="unqualified" version="01.00" xmlns:types="http://services.tint.telekom.net/EnterpSupp/EnterpEffAndPrjMgmt/PurchaseDocumentDistribute_v01.00/types">
      <!-- ****************************************************************** -->
      <xsd:import namespace="http://schemas.telekom.net/csdg_v01.01" schemaLocation="../../../../xsds-csdg/csdg_v01.01.xsd" />
      <xsd:import namespace="http://services.tint.telekom.net/EnterpSupp/EnterpEffAndPrjMgmt/PurchaseDocumentDistribute_v01.00/types" schemaLocation="PurchaseDocumentDistribute_v01.00.xsd" />
      <!-- ****************************************************************** -->
      <xsd:element name="distributeChangesAsync" type="types:DistributeChangesAsyncType" />
    </xsd:schema>
  </types>
  <!-- ****************************************************************** -->
  <!-- Messages : -->
  <!-- ****************************************************************** -->
  <message name="DistributeChangesAsync">
    <part name="parameters" element="tns:distributeChangesAsync" />
  </message>
  <message name="EmptyTechnicalResponse">
    <part name="parameters" element="csdg:empty" />
  </message>
  <message name="TechnicalFault">
    <part name="parameters" element="csdg:technicalFault" />
  </message>
  <!-- ****************************************************************** -->
  <!-- PortTypes : -->
  <!-- ****************************************************************** -->
  <!-- Consumer : -->
  <portType name="PurchaseDocumentDistributeConsumer">
    <operation name="distributeChangesAsync">
      <documentation>
        <doc:operation mep="Notification" access="ReadOnly">
          <doc:description>
						-------------------------- @TODO:DESCRIBE_ME - Operation "distributeChangesAsync" -----------------------------
					</doc:description>
        </doc:operation>
      </documentation>
      <input message="tns:DistributeChangesAsync" />
      <output message="tns:EmptyTechnicalResponse" />
      <fault message="tns:TechnicalFault" name="TechnicalFault" />
    </operation>
  </portType>
</definitions>