//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Terminal.Languages {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LangResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangResources() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Terminal.Languages.LangResources", typeof(LangResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Application.
        /// </summary>
        public static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný TMH Terminal.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Build.
        /// </summary>
        public static string Build {
            get {
                return ResourceManager.GetString("Build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Create order.
        /// </summary>
        public static string CreateOrder {
            get {
                return ResourceManager.GetString("CreateOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Czech.
        /// </summary>
        public static string cs {
            get {
                return ResourceManager.GetString("cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Data transfer.
        /// </summary>
        public static string DataTransfer {
            get {
                return ResourceManager.GetString("DataTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Developer Contact.
        /// </summary>
        public static string DeveloperContact {
            get {
                return ResourceManager.GetString("DeveloperContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Libor.Svoboda@KlikneteZde.cz.
        /// </summary>
        public static string DeveloperEmail {
            get {
                return ResourceManager.GetString("DeveloperEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Libor Svoboda.
        /// </summary>
        public static string DeveloperName {
            get {
                return ResourceManager.GetString("DeveloperName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný +420 724 986 873.
        /// </summary>
        public static string DeveloperPhone {
            get {
                return ResourceManager.GetString("DeveloperPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Distributor webpage.
        /// </summary>
        public static string DistributorWeb {
            get {
                return ResourceManager.GetString("DistributorWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný https://expedis.cz/.
        /// </summary>
        public static string DistributorWebPage {
            get {
                return ResourceManager.GetString("DistributorWebPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný English.
        /// </summary>
        public static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Equipment number.
        /// </summary>
        public static string EquipmentNumber {
            get {
                return ResourceManager.GetString("EquipmentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Fast goods info.
        /// </summary>
        public static string FastGoodsInfo {
            get {
                return ResourceManager.GetString("FastGoodsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Fault report print.
        /// </summary>
        public static string FaultReportPrint {
            get {
                return ResourceManager.GetString("FaultReportPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Good receipt from PO.
        /// </summary>
        public static string GoodReceiptFromPO {
            get {
                return ResourceManager.GetString("GoodReceiptFromPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Goods Issue.
        /// </summary>
        public static string GoodsIssue {
            get {
                return ResourceManager.GetString("GoodsIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Goods receipt.
        /// </summary>
        public static string GoodsReceipt {
            get {
                return ResourceManager.GetString("GoodsReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Insert part M/N or UIID.
        /// </summary>
        public static string InsertMaterialId {
            get {
                return ResourceManager.GetString("InsertMaterialId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Insert PN/MN.
        /// </summary>
        public static string InsertPnMn {
            get {
                return ResourceManager.GetString("InsertPnMn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Insert PN/MN or part of description.
        /// </summary>
        public static string InsertPnMnOrDescription {
            get {
                return ResourceManager.GetString("InsertPnMnOrDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Insert PN/MN/UIID.
        /// </summary>
        public static string InsertPnMnUiid {
            get {
                return ResourceManager.GetString("InsertPnMnUiid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Insert quantity.
        /// </summary>
        public static string InsertQuantity {
            get {
                return ResourceManager.GetString("InsertQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Insert serial number.
        /// </summary>
        public static string InsertSerialNumber {
            get {
                return ResourceManager.GetString("InsertSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Insert site number.
        /// </summary>
        public static string InsertSiteNumber {
            get {
                return ResourceManager.GetString("InsertSiteNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný InsertTicketNumber.
        /// </summary>
        public static string InsertTicketNumber {
            get {
                return ResourceManager.GetString("InsertTicketNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Issue.
        /// </summary>
        public static string Issue {
            get {
                return ResourceManager.GetString("Issue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný ItemDescription.
        /// </summary>
        public static string ItemDescription {
            get {
                return ResourceManager.GetString("ItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Item not exist.
        /// </summary>
        public static string ItemNotExist {
            get {
                return ResourceManager.GetString("ItemNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Item not founded.
        /// </summary>
        public static string ItemNotFound {
            get {
                return ResourceManager.GetString("ItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Label.
        /// </summary>
        public static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný IP label printer.
        /// </summary>
        public static string LabelPrinterIp {
            get {
                return ResourceManager.GetString("LabelPrinterIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Port label printer.
        /// </summary>
        public static string LabelPrinterPort {
            get {
                return ResourceManager.GetString("LabelPrinterPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Label printing.
        /// </summary>
        public static string LabelPrinting {
            get {
                return ResourceManager.GetString("LabelPrinting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný LDAP DN.
        /// </summary>
        public static string ldapDN {
            get {
                return ResourceManager.GetString("ldapDN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný LDAP Port.
        /// </summary>
        public static string ldapPort {
            get {
                return ResourceManager.GetString("ldapPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný LDAP server IP.
        /// </summary>
        public static string ldapServerIp {
            get {
                return ResourceManager.GetString("ldapServerIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Load.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Login failed.
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný LOGON.
        /// </summary>
        public static string Logon {
            get {
                return ResourceManager.GetString("Logon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Material is not serializable.
        /// </summary>
        public static string MaterialIsNotSerializable {
            get {
                return ResourceManager.GetString("MaterialIsNotSerializable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Menu Items.
        /// </summary>
        public static string MenuItems {
            get {
                return ResourceManager.GetString("MenuItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný M/N.
        /// </summary>
        public static string MN {
            get {
                return ResourceManager.GetString("MN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Place.
        /// </summary>
        public static string Place {
            get {
                return ResourceManager.GetString("Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný P/N.
        /// </summary>
        public static string PN {
            get {
                return ResourceManager.GetString("PN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Quantity blocked.
        /// </summary>
        public static string QuantityBlocked {
            get {
                return ResourceManager.GetString("QuantityBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Quantity free.
        /// </summary>
        public static string QuantityFree {
            get {
                return ResourceManager.GetString("QuantityFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Quantity in transfer.
        /// </summary>
        public static string QuantityInTransfer {
            get {
                return ResourceManager.GetString("QuantityInTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Refresh interval.
        /// </summary>
        public static string RefreshInterval {
            get {
                return ResourceManager.GetString("RefreshInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Report location.
        /// </summary>
        public static string ReportLocation {
            get {
                return ResourceManager.GetString("ReportLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Report printer IP.
        /// </summary>
        public static string ReportPrinterIp {
            get {
                return ResourceManager.GetString("ReportPrinterIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Report printer Port.
        /// </summary>
        public static string ReportPrinterPort {
            get {
                return ResourceManager.GetString("ReportPrinterPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Report site.
        /// </summary>
        public static string ReportSite {
            get {
                return ResourceManager.GetString("ReportSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný roleDN.
        /// </summary>
        public static string roleDN {
            get {
                return ResourceManager.GetString("roleDN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný SAP Settings.
        /// </summary>
        public static string SapSettings {
            get {
                return ResourceManager.GetString("SapSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Scan.
        /// </summary>
        public static string Scan {
            get {
                return ResourceManager.GetString("Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Scan code.
        /// </summary>
        public static string ScanCode {
            get {
                return ResourceManager.GetString("ScanCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Scanner.
        /// </summary>
        public static string Scaner {
            get {
                return ResourceManager.GetString("Scaner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Select Area.
        /// </summary>
        public static string SelectArea {
            get {
                return ResourceManager.GetString("SelectArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Select language.
        /// </summary>
        public static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Select or create order.
        /// </summary>
        public static string SelectOrCreateOrder {
            get {
                return ResourceManager.GetString("SelectOrCreateOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Select source location.
        /// </summary>
        public static string SelectSourceLocation {
            get {
                return ResourceManager.GetString("SelectSourceLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Select target location.
        /// </summary>
        public static string SelectTargetLocation {
            get {
                return ResourceManager.GetString("SelectTargetLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Serial number does&apos;t exist.
        /// </summary>
        public static string SerialNumberNotExist {
            get {
                return ResourceManager.GetString("SerialNumberNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Site number not exist.
        /// </summary>
        public static string SiteNumberNotExist {
            get {
                return ResourceManager.GetString("SiteNumberNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Slovak.
        /// </summary>
        public static string sk {
            get {
                return ResourceManager.GetString("sk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný S/N.
        /// </summary>
        public static string SN {
            get {
                return ResourceManager.GetString("SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Stock taking.
        /// </summary>
        public static string StockTaking {
            get {
                return ResourceManager.GetString("StockTaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Target Location.
        /// </summary>
        public static string TargetLocation {
            get {
                return ResourceManager.GetString("TargetLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Task number not exist.
        /// </summary>
        public static string TaskNumberNotExist {
            get {
                return ResourceManager.GetString("TaskNumberNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Transfer receipt.
        /// </summary>
        public static string TransferReceipt {
            get {
                return ResourceManager.GetString("TransferReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Transfer release.
        /// </summary>
        public static string TransferRelease {
            get {
                return ResourceManager.GetString("TransferRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný UIID.
        /// </summary>
        public static string UIID {
            get {
                return ResourceManager.GetString("UIID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný User name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Warehouse name.
        /// </summary>
        public static string WarehouseName {
            get {
                return ResourceManager.GetString("WarehouseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Warehouse number.
        /// </summary>
        public static string WarehouseNumber {
            get {
                return ResourceManager.GetString("WarehouseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Warehouse stocks.
        /// </summary>
        public static string WarehouseStocks {
            get {
                return ResourceManager.GetString("WarehouseStocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
