<?xml version="1.0" encoding="UTF-8"?>
<definitions name="EquipmentDistribute" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:doc="http://schemas.telekom.net/csdg-service-documentation_v01.01" xsi:schemaLocation="http://schemas.telekom.net/csdg-service-documentation_v01.01 ../../../../xsds-csdg/csdg-service-documentation_v01.01.xsd" xmlns:csdg="http://schemas.telekom.net/csdg_v01.01" targetNamespace="http://services.tint.telekom.net/EnterpSupp/EnterpEffAndPrjMgmt/EquipmentDistribute_v01.00" xmlns:tns="http://services.tint.telekom.net/EnterpSupp/EnterpEffAndPrjMgmt/EquipmentDistribute_v01.00">
  <documentation>
    <!-- !! @AUTHORS: INCREMENT VERSION NUMBER AND ADAPT "kind-of-creation" AFTER CHANGES !! -->
    <doc:service governance-area="tint" domain="EnterpSupp" functional-component="EnterpEffAndPrjMgmt" version="01.00.000" version-date="2017-05-10" isLogicalService="true">
      <doc:description>
Updated on 01.06.2017 10:45:52, UTC
14117	01.06.2017 10:04:33	Version fix. MOM deleted

Updated on 10.05.2017 08:59:11, UTC
13855	10.05.2017 08:58:13	Corrections for CSDG validator

Updated on 10.03.2016 09:09:31, UTC
7953	10.03.2016 09:09:09	ManufacturerModelNumber-&gt;ManufacturerPartNumber
+ConnectedToFlocId
+SupplierVendorId

Updated on 04.03.2016 09:06:52, UTC
7268	22.02.2016 13:18:50	Some fields related to warranty are now integers
7259	20.02.2016 15:36:53	Changes for material documents

Updated on 09.09.2015 17:21:36, UTC
6080	09.09.2015 17:21:05	Occurrence changed from 0..1 to 1..1 for base xsd types. Pattern \d+ removed

Updated on 27.05.2015 18:36:12, UTC
5442	20.05.2015 16:01:55	Byte order mark deleted. utf-8 -&gt; UTF-8
5437	20.05.2015 09:35:37	Version updated for wsdls for 15C
5412	15.05.2015 19:53:07	Serial number fields renamed
5344	07.05.2015 14:34:42	
4676	23.01.2015 09:37:13	Cardinality of CreatedOrUpdated in DT_EquipmentDistributionData changed from [0..n] to [0..1]
4413	25.11.2014 11:59:17	CSDG. One operation = one service.
4355	20.11.2014 16:07:07	Changes in wsdl and updating TDs to CSDG
4168	06.11.2014 12:11:59	New wsdls
3956	16.10.2014 11:20:18	Fixed according to validator
3693	24.09.2014 15:13:12	SoaBP wsdls

				-------------------------- @TODO:DESCRIBE_ME - Service "EquipmentDistribute" -----------------------------
			</doc:description>
      <doc:designer>mailto:Augustinus.Deimel@telekom.de</doc:designer>
      <doc:kind-of-creation>GENERATED</doc:kind-of-creation>
      <doc:change predecessorVersion="01.00.000" by="A.Deimel" date="2014-10-20" doc:lang="en">14117</doc:change>
    </doc:service>
  </documentation>
  <types>
    <xsd:schema targetNamespace="http://services.tint.telekom.net/EnterpSupp/EnterpEffAndPrjMgmt/EquipmentDistribute_v01.00" elementFormDefault="qualified" attributeFormDefault="unqualified" version="01.00" xmlns:types="http://services.tint.telekom.net/EnterpSupp/EnterpEffAndPrjMgmt/EquipmentDistribute_v01.00/types">
      <!-- ****************************************************************** -->
      <xsd:import namespace="http://schemas.telekom.net/csdg_v01.01" schemaLocation="../../../../xsds-csdg/csdg_v01.01.xsd" />
      <xsd:import namespace="http://services.tint.telekom.net/EnterpSupp/EnterpEffAndPrjMgmt/EquipmentDistribute_v01.00/types" schemaLocation="EquipmentDistribute_v01.00.xsd" />
      <!-- ****************************************************************** -->
      <xsd:element name="distributeChangesAsync" type="types:DistributeChangesAsyncType" />
    </xsd:schema>
  </types>
  <!-- ****************************************************************** -->
  <!-- Messages : -->
  <!-- ****************************************************************** -->
  <message name="DistributeChangesAsync">
    <part name="parameters" element="tns:distributeChangesAsync" />
  </message>
  <message name="EmptyTechnicalResponse">
    <part name="parameters" element="csdg:empty" />
  </message>
  <message name="TechnicalFault">
    <part name="parameters" element="csdg:technicalFault" />
  </message>
  <!-- ****************************************************************** -->
  <!-- PortTypes : -->
  <!-- ****************************************************************** -->
  <!-- Consumer : -->
  <portType name="EquipmentDistributeConsumer">
    <operation name="distributeChangesAsync">
      <documentation>
        <doc:operation mep="Notification" access="ReadOnly">
          <doc:description>
						-------------------------- @TODO:DESCRIBE_ME - Operation "distributeChangesAsync" -----------------------------
					</doc:description>
        </doc:operation>
      </documentation>
      <input message="tns:DistributeChangesAsync" />
      <output message="tns:EmptyTechnicalResponse" />
      <fault message="tns:TechnicalFault" name="TechnicalFault" />
    </operation>
  </portType>
</definitions>